# Generated by Django 5.2.1 on 2025-05-26 17:24

import django.db.models.deletion
import site_recipes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Название блюда",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(verbose_name="Описание блюда"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to=site_recipes.models.image_directory,
                verbose_name="Название блюда",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(verbose_name="Название блюда"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="steps",
            field=models.TextField(verbose_name="Шаги приготовления блюда"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="time_cooking",
            field=models.TimeField(verbose_name="Время приготовления блюда"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название блюда"),
        ),
    ]
