# Generated by Django 5.2.1 on 2025-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_recipes", "0004_alter_recipe_time_cooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.CharField(verbose_name="Автор рецепта"),
        ),
    ]
