# Generated by Django 5.2.1 on 2025-05-26 17:25

import django.db.models.deletion
import site_recipes_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_recipes_app", "0002_alter_recipe_author_alter_recipe_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to=site_recipes_app.models.image_directory,
                verbose_name="Изображение блюда",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(verbose_name="Ингредиенты для блюда"),
        ),
    ]
