# Generated by Django 5.2.1 on 2025-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_recipes_app", "0003_alter_recipe_author_alter_recipe_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="time_cooking",
            field=models.CharField(verbose_name="Время приготовления блюда"),
        ),
    ]
