# Generated by Django 5.2.1 on 2025-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_recipes_app", "0007_alter_recipe_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Категория")),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(
                to="site_recipes_app.category", verbose_name="Категория"
            ),
        ),
    ]
