# Generated by Django 5.2.1 on 2025-06-13 17:22

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=recipes.models.image_directory,
                verbose_name="Изображение блюда",
            ),
        ),
    ]
